name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [Debian]
    steps:
    - name: Load Binary
      id: detect
      uses: actions/cache@v3
      with:
        path: detect-linux-x86_64, detect-linux-aarch64
        key: detect-${{ github.sha }}
        fail-on-cache-miss: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: detect-linux-x86_64, detect-linux-aarch64
